/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatComposer: typeof import('./components/chat/workspace/components/ChatComposer.vue')['default']
    ChatMessageBubble: typeof import('./components/chat/ChatMessageBubble.vue')['default']
    ChatMessagePane: typeof import('./components/chat/workspace/components/ChatMessagePane.vue')['default']
    ChatPageLayout: typeof import('./components/chat/ChatPageLayout.vue')['default']
    ChatWorkspace: typeof import('./components/chat/ChatWorkspace.vue')['default']
    ConversationSidebar: typeof import('./components/chat/workspace/components/ConversationSidebar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    GameChatEntryPanel: typeof import('./components/chat/GameChatEntryPanel.vue')['default']
    KnowledgeFileList: typeof import('./components/chat/knowledge-panel/components/KnowledgeFileList.vue')['default']
    KnowledgePreviewDialog: typeof import('./components/chat/knowledge-panel/components/KnowledgePreviewDialog.vue')['default']
    KnowledgeSessionFilePanel: typeof import('./components/chat/KnowledgeSessionFilePanel.vue')['default']
    ProductCard: typeof import('./components/portal/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
