spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/spring_ai_demo?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: true
    enabled: true

  application:
    name: spring-ai-demo

  ai:
    chat:
      client:
        enabled: false
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-020127f24b3742b5bb3094b98dead8bb
      chat:
        options:
          model: glm-4.7
server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

logging:
  level:
    org.springframework.ai: DEBUG
    com.aliyun: DEBUG